### ISSUE TITLE
Incompatible with Dalamud v9/6.5

### ISSUE THREAD

**Issue by GiacomoLaw** [Arrenton/AudibleCharacterStatus#12]

**Comment by GiacomoLaw** [comment]
Will take a look at updating this. Will probably require a bit of reviewing as I am rusty with CPP and haven't played with Dalamud too much.

**Comment by jpsraiden** [comment]
I really rely on audio cues, any idea when this will be updated? Thanks

**Comment by himea-saito** [comment]
Also interested in this! Might be time to learn some C++ and fork as it looks like this project might be abandoned...

**Comment by Arrenton** [comment]
There will be an update sometime today

**Comment by Arrenton** [comment]
Update has been pushed to the plugin manager. Whenever it gets passed through by the maintainers, it'll be up.

**Comment by GiacomoLaw** [comment]
Awesome thanks so much!
