### ISSUE TITLE
Update for Dawntrail patch

### ISSUE THREAD

**Issue by jpsraiden** [Arrenton/AudibleCharacterStatus#15]
Hi, would it be possible to have this updated to the latest patch? Thanks

**Comment by RiledUp42** [comment]
Seconding this request. I use this plugin for accessibility, so I'd really appreciate an update.

**Comment by Arrenton** [comment]
Currently trying to push an update to the plugin downloader.

Had a lot of trouble getting it to work on their plugin updater this time.

I apologize that it took so long, and I appreciate the patience. I don't play the game anymore and I had no idea this plugin would even be used haha.

**Comment by Arrenton** [comment]
Update has been posted to the plugin manager.
