### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by BrakTap** [Arrenton/AudibleCharacterStatus#2]
I don't know where else to give my thanks, this is probably not nearly as funny as other people might think, but getting murdered in P4S has never been more funny to me, so yeah thank you! for this wonderfull plugin! 
![bruh](https://user-images.githubusercontent.com/98245129/173221822-75b81b61-cca3-46a0-a48e-ca36d2eb5604.png)

**Comment by Arrenton** [comment]
Thanks for the support! lol
