### ISSUE TITLE
[BUG] Plugin crash on setting change

### ISSUE THREAD

**Issue by QuentinMcCarthy** [Arrenton/AudibleCharacterStatus#3]
I am unsure of the exact cause, but changing the plugin's settings at times causes the plugin to crash, only being fixed by either a game restart or reinstalling the plugin to restart it.

The times it has occurred thus far I've been both in combat and only changing the hp% setting.

**Comment by QuentinMcCarthy** [comment]
After a bit of testing I've discovered that it is NOT combat causing it, nor the setting being changed. The plugin will always crash when hitting the "save" button. Changing settings itself does not crash the plugin, but hitting "save" does.

**Comment by Arrenton** [comment]
Would you be able to check the log for the error?
You can type /xllog to bring up the logger.

**Comment by Arrenton** [comment]
Fixed in latest commit. Fix will be in 1.0.0.2 whenever it gets published.
