### ISSUE TITLE
[request] option for alarm only when in raid / dungeon / trial / instance / combat

### ISSUE THREAD

**Issue by thoccavelli** [Arrenton/AudibleCharacterStatus#5]
Love the plugin, esp the ability to customize sound file alert!

Would it be possible to have an option to enable alarm only in raid, dungeon, trial, instance or combat?

The alarm goes off whenever I switch jobs/classes outside of combat / instances.  Like when you switch from DoH/DoL to healer, low MP alarm goes off since combat job health & MP pool is so much bigger than DoH/DoL. Thank you very much!

**Comment by Arrenton** [comment]
There was an option added to only play sounds when in combat. #8
