### ISSUE TITLE
Could someone update this for 6.3 pretty please?

### ISSUE THREAD

**Issue by KaladinMekhar** [Arrenton/AudibleCharacterStatus#9]
Following the recent patch and Dalamud update, this doesnt work anymore. Dalamud says the plugin is outdated. Would be great if someone could update this for 6.3 please. Thanks

**Comment by Kitsune-Witch** [comment]
any word on this? the plugin has been updated to API 8 for a month now and it still won't update on dalamud

**Comment by Arrenton** [comment]
Working on it. There are issues with the sound api not working with their new plugin update system.

I think I did just successfully get it on the testing channel though.
